### ISSUE TITLE
ENV_NAME in envvars config file is not correct

### ISSUE THREAD

**Issue by informaticienzero** [0xadada/dockdj#6]
In current DEV config file, it is written `"ENV_NAME": "prod"`. Shouldn't it be `"dev"` ?

**Comment by 0xadada** [comment]
in which file?

**Comment by informaticienzero** [comment]
In `dockdj/environments/dev/01_envvars.config``.

**Comment by 0xadada** [comment]
Not necessarily, the way i use it, once deployed to EB, the is a [Blue-Green Deployment](http://martinfowler.com/bliki/BlueGreenDeployment.html) where both are deployed to EB as "prod" but in different EB environments. I dont really use the "dev" config file, so feel free to edit yours.
